Import Upstream version 3.1.0

diff --git a/prog/pwm/fancontrol b/prog/pwm/fancontrol
--- a/prog/pwm/fancontrol
+++ b/prog/pwm/fancontrol
@@ -1,8 +1,9 @@
 #!/bin/bash
 #
 # Simple script implementing a temperature dependent fan speed control
+# Supported Linux kernel versions: 2.6.5 and later
 #
-# Version 0.67
+# Version 0.68
 #
 # Usage: fancontrol [CONFIGFILE]
 #
@@ -18,7 +19,7 @@
 #
 #
 #    Copyright 2003 Marius Reiner <marius.reiner@hdev.de>
-#    Copyright (C) 2007-2008 Jean Delvare <khali@linux-fr.org>
+#    Copyright (C) 2007-2009 Jean Delvare <khali@linux-fr.org>
 #
 #    This program is free software; you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -42,17 +43,16 @@ PIDFILE="/var/run/fancontrol.pid"
 #DEBUG=1
 MAX=255
 
-if [ -f "$PIDFILE" ]
-then
-	echo "File $PIDFILE exists, is fancontrol already running?"
-	exit 1
-fi
-echo $$ > "$PIDFILE"
-
 declare -i pwmval
 
 function LoadConfig {
 	echo "Loading configuration from $1 ..."
+	if [ ! -r "$1" ]
+	then
+		echo "Error: Can't read configuration file"
+		exit 1
+	fi
+
 	# grep configuration from file
 	INTERVAL=`egrep '^INTERVAL=.*$' $1 | sed -e 's/INTERVAL=//g'`
 	FCTEMPS=`egrep '^FCTEMPS=.*$' $1 | sed -e 's/FCTEMPS=//g'`
@@ -64,7 +64,7 @@ function LoadConfig {
 	FCFANS=`egrep '^FCFANS=.*$' $1 | sed -e 's/FCFANS=//g'`
 	MINPWM=`egrep '^MINPWM=.*$' $1 | sed -e 's/MINPWM=//g'`
 	MAXPWM=`egrep '^MAXPWM=.*$' $1 | sed -e 's/MAXPWM=//g'`
-	
+
 	# Check whether all mandatory settings are set
 	if [[ -z ${INTERVAL} || -z ${FCTEMPS} || -z ${MINTEMP} || -z ${MAXTEMP} || -z ${MINSTART} || -z ${MINSTOP} ]]
 	then
@@ -79,10 +79,10 @@ function LoadConfig {
 	fi
 
 	# write settings to arrays for easier use and print them
-        echo
+	echo
 	echo "Common settings:"
 	echo "  INTERVAL=$INTERVAL"
-						
+
 	let fcvcount=0
 	for fcv in $FCTEMPS
 	do
@@ -153,90 +153,80 @@ function LoadConfig {
 }
 
 if [ -f "$1" ]
-then 
+then
 	LoadConfig $1
 else
 	LoadConfig /etc/fancontrol
 fi
 
-DIR=/proc/sys/dev/sensors
+# Detect if config file uses the hwmon class or not yet
+if echo "${AFCPWM[0]}" | egrep -q '^hwmon[0-9]'
+then
+	DIR=/sys/class/hwmon
+else
+	DIR=/sys/bus/i2c/devices
+fi
+
 if [ ! -d $DIR ]
 then
-	# For Linux 2.6, detect if config file uses the hwmon class or not yet
-	if echo "${AFCPWM[0]}" | egrep -q '^hwmon[0-9]'
-	then
-		SDIR=/sys/class/hwmon
-	else
-		SDIR=/sys/bus/i2c/devices
-	fi
-
-	if [ ! -d $SDIR ]
-	then
-		echo $0: 'No sensors found! (did you load the necessary modules?)'
-		exit 1
-	else
-		SYSFS=1
-		DIR=$SDIR
-	fi	
+	echo $0: 'No sensors found! (did you load the necessary modules?)'
+	exit 1
 fi
 cd $DIR
+
+if [ -f "$PIDFILE" ]
+then
+	echo "File $PIDFILE exists, is fancontrol already running?"
+	exit 1
+fi
+echo $$ > "$PIDFILE"
 
 # $1 = pwm file name
 function pwmdisable()
 {
-	if [ -n "$SYSFS" ]
+	ENABLE=${1}_enable
+	# No enable file? Just set to max
+	if [ ! -f $ENABLE ]
 	then
-		ENABLE=${1}_enable
-		# No enable file? Just set to max
-		if [ ! -f $ENABLE ]
-		then
-			echo $MAX > $1
-			return 0
-		fi
-
-		# Try pwmN_enable=0
-		echo 0 > $ENABLE 2> /dev/null
-		if [ `cat $ENABLE` -eq 0 ]
-		then
-			# Success
-			return 0
-		fi
-
-		# It didn't work, try pwmN_enable=1 pwmN=255
-		echo 1 > $ENABLE 2> /dev/null
 		echo $MAX > $1
-		if [ `cat $ENABLE` -eq 1 -a `cat $1` -ge 190 ]
-		then
-			# Success
-			return 0
-		fi
-
-		# Nothing worked
-		echo "$ENABLE stuck to" `cat $ENABLE` >&2
-		return 1
-	else
-		echo $MAX 0 > $1
+		return 0
 	fi
+
+	# Try pwmN_enable=0
+	echo 0 > $ENABLE 2> /dev/null
+	if [ `cat $ENABLE` -eq 0 ]
+	then
+		# Success
+		return 0
+	fi
+
+	# It didn't work, try pwmN_enable=1 pwmN=255
+	echo 1 > $ENABLE 2> /dev/null
+	echo $MAX > $1
+	if [ `cat $ENABLE` -eq 1 -a `cat $1` -ge 190 ]
+	then
+		# Success
+		return 0
+	fi
+
+	# Nothing worked
+	echo "$ENABLE stuck to" `cat $ENABLE` >&2
+	return 1
 }
 
 # $1 = pwm file name
 function pwmenable()
 {
-	if [ "$SYSFS" = "1" ]
+	ENABLE=${1}_enable
+	if [ -f $ENABLE ]
 	then
-		ENABLE=${1}_enable
-		if [ -f $ENABLE ]
+		echo 1 > $ENABLE 2> /dev/null
+		if [ $? -ne 0 ]
 		then
-			echo 1 > $ENABLE 2> /dev/null
-			if [ $? -ne 0 ]
-			then
-				return 1
-			fi
+			return 1
 		fi
-		echo $MAX > $1
-	else
-		echo $MAX 1 > $1
 	fi
+	echo $MAX > $1
 }
 
 function restorefans()
@@ -267,24 +257,18 @@ function UpdateFanSpeeds {
 		pwmo=${AFCPWM[$fcvcount]}
 		tsens=${AFCTEMP[$fcvcount]}
 		fan=${AFCFAN[$fcvcount]}
-		mint=${AFCMINTEMP[$fcvcount]}
-		maxt=${AFCMAXTEMP[$fcvcount]}
+		let mint="${AFCMINTEMP[$fcvcount]}*1000"
+		let maxt="${AFCMAXTEMP[$fcvcount]}*1000"
 		minsa=${AFCMINSTART[$fcvcount]}
 		minso=${AFCMINSTOP[$fcvcount]}
 		minpwm=${AFCMINPWM[$fcvcount]}
 		maxpwm=${AFCMAXPWM[$fcvcount]}
-		
+
 		read tval < ${tsens}
 		if [ $? -ne 0 ]
 		then
 			echo "Error reading temperature from $DIR/$tsens"
 			restorefans 1
-		fi
-		if [ "$SYSFS" = "1" ]
-		then
-			let tval="($tval+500)/1000"
-		else
-			tval=`echo ${tval} | cut -d' ' -f3 | cut -d'.' -f1`
 		fi
 
 		read pwmpval < ${pwmo}
@@ -293,11 +277,7 @@ function UpdateFanSpeeds {
 			echo "Error reading PWM value from $DIR/$pwmo"
 			restorefans 1
 		fi
-		if [ "$SYSFS" != "1" ]
-		then
-			pwmpval=`echo ${pwmpval} | cut -d' ' -f1`
-		fi
-		
+
 		# If fanspeed-sensor output shall be used, do it
 		if [[ -n ${fan} ]]
 		then
@@ -307,14 +287,10 @@ function UpdateFanSpeeds {
 				echo "Error reading Fan value from $DIR/$fan"
 				restorefans 1
 			fi
-			if [ "$SYSFS" != "1" ]
-			then
-				fanval=`echo ${fanval} | cut -d' ' -f2`
-			fi
 		else
 			fanval=1  # set it to a non zero value, so the rest of the script still works
 		fi
-		
+
 		# debug info
 		if [ "$DEBUG" != "" ]
 		then
@@ -331,19 +307,20 @@ function UpdateFanSpeeds {
 			echo "pwmpval=$pwmpval"
 			echo "fanval=$fanval"
 		fi
-		
+
 		if (( $tval <= $mint ))
 		  then pwmval=$minpwm # below min temp, use defined min pwm
 		elif (( $tval >= $maxt ))
 		  then pwmval=$maxpwm # over max temp, use defined max pwm
-		else 
+		else
 		  # calculate the new value from temperature and settings
 		  pwmval="(${tval}-${mint})*(${maxpwm}-${minso})/(${maxt}-${mint})+${minso}"
 		  if [ $pwmpval -eq 0 -o $fanval -eq 0 ]
 		  then # if fan was stopped start it using a safe value
 		  	echo $minsa > $pwmo
 			# Sleep while still handling signals
-			read < <(exec sleep 1)
+			sleep 1 &
+			wait $!
 		  fi
 		fi
 		echo $pwmval > $pwmo # write new value to pwm output
@@ -381,5 +358,6 @@ while true
 do
 	UpdateFanSpeeds
 	# Sleep while still handling signals
-	read < <(exec sleep $INTERVAL)
+	sleep $INTERVAL &
+	wait $!
 done
